openapi: 3.1.0
info:
  title: Ingredient
  #  description: Title
  version: 1.0.0
servers:
  - url: 'https://localhost:8080'


components:
  responses:
    ingredientNotFound:
      description: ingredient not found.
      content:
        text/plain:
          schema:
            type: string
            example: "Ingredient.id=1 is not found"

  schemas:
    ingredient:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "tomate"
        category:
          type: string
          enum: [ VEGETABLE, ANIMAL, MARINE, DAIRY, OTHER ]
        price:
          type: number
          example: 300.0
        stockMovement:
          type: array
          items:
            $ref: "#/components/schemas/stockMovement"
    stockMovement:
      type: object
      properties:
        id:
          type: integer
          example: 1
        stockValue:
          $ref: "#/components/schemas/stockValue"
        movement_type:
          type: string
          enum: [ in,out ]
        creation_datetime:
          type: string
          format: date
    stockValue:
      type: object
      properties:
        quantity:
          type: number
          example: 1.4
        unit:
          type: string
          enum: [ PCS, KG, L ]

    dishes:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: gateau
        price:
          type: number
          example: 300.0
        dishType:
          type: string
          enum: [ STARTER, MAIN, DESSERT ]
        ingredients:
          $ref: "#/components/schemas/ingredient"



paths:
  /ingredients:
    get:
      description: return all ingredient
      responses:
        '200':
          description: a list of ingredient
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ingredient"
  /ingredients/{id}:
    get:
      description: find ingredient by id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1

      responses:
        '200':
          description: find ingredient by id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ingredient"
        '404':
          $ref: "#/components/responses/ingredientNotFound"


  /ingredients/{id}/stock:
    get:
      description: get stock of ingredient at a specific date
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1

        - name: at
          in: query
          required: true
          schema:
            type: string
            format: date

        - name: unit
          in: query
          required: true
          schema:
            type: string
            enum: [ PCS, KG, L ]
      responses:
        '200':
          description: return quantity and unity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/stockValue"
        '404':
          $ref: "#/components/responses/ingredientNotFound"
        '400':
          description: bad request
          content:
            text/plain:
              schema:
                type: string
                example: "Either mandatory query parameter `at` or `unit` is not provided."

  /dishes:
    get:
      responses:
        '200':
          description: return all dishes
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/dishes"

  /dishes/{id}/ingredients:
    put:
      description:  Associate or dissociate ingredient
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/ingredient"

      responses:
        '200':
          description: updated list of ingredients associated to the dish
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/dishes"
        '404':
          description: dish not found
          content:
            text/plain:
              schema:
                type: string
                example: "Dish.id=1 is not found"
        '400':
          description: bad request — request body is missing
          content:
            text/plain:
              schema:
                type: string
                example: "Request body is required and must contain a list of ingredients."











